local options = {
	autoindent = true,
	backup = false,
	breakindent = true,
	clipboard = "unnamedplus", -- Access system clipboard
	cmdheight = 0,
	completeopt = { "menu", "noselect", "preview" },
	conceallevel = 0,
	confirm = true,
	cursorline = true,
	expandtab = true,
	fileencoding = "utf-8",
	fillchars = [[eob: ,fold: ,foldopen:,foldsep: ,foldclose:]],
	foldcolumn = "1",
	foldenable = true,
	foldlevel = 99,
	foldlevelstart = 99,
	formatoptions = "jqlnt",
	hidden = true,
	hlsearch = true,
	ignorecase = true,
	inccommand = "nosplit",
	joinspaces = false,
	laststatus = 3,
	list = true,
	mouse = "a",
	number = true,
	numberwidth = 4,
	pumheight = 10,
	relativenumber = true,
	scrollback = 100000,
	scrolloff = 8,
	sessionoptions = { "buffers", "curdir", "tabpages", "winsize" },
	shiftround = true,
	shiftwidth = 2,
	showcmd = false,
	showmode = false,
	showtabline = 2,
	sidescrolloff = 8,
	signcolumn = "yes",
	smartcase = true,
	smartindent = true,
	splitbelow = true,
	splitkeep = "screen",
	splitright = true,
	swapfile = false,
	tabstop = 2,
	termguicolors = true,
	timeoutlen = 300,
	title = true,
	undofile = true,
	updatetime = 200,
	wrap = false,
	wildmode = "longest:full,full",
	writebackup = false,
}

vim.opt.shortmess:append({ W = true, I = true, c = true, C = true })

for k, v in pairs(options) do
	vim.opt[k] = v
end

vim.cmd("set whichwrap+=<,>,[,],h,l")
vim.cmd([[set iskeyword+=-]])
